version: "3.10"

services:
  db:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
  app:
    build: app
    command:
      bash -c "./wait-for-it.sh $POSTGRES_HOST:$POSTGRES_PORT && 
      python manage.py migrate --run-syncdb && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
